### ISSUE TITLE
setup.py should not import pyscreeze

### ISSUE THREAD

**Issue by SpotlightKid** [asweigart/pyscreeze#13]
`setup.py` imports `pyscreeze` to get the version info. This then fails if the dependency `PIL` (`Pillow`) is not already installed when setup.py is run (which may be by `pip`).

Solution: put version info (and optionally any other distribution metadata) in an extra module file (e.g. `version.py`, `release.py` or `metadata.py`)  and _do not import_ it, but read it with:

```
data = {}
version_info = 'pyscreeze/version.py'
exec(compile(open(version_info).read(), version_info, 'exec'), {}, data)
version = data['__version__']
```

BTW, `from pyscreeze.version import __version__ as version` does also not work, since this will implicitly import `pyscreeze/__init__.py`.

This also prevents the possible problem where `setup.py` is run with an already installed version of pyscreeze and the version info is read from the installed package, rather from the directory, from which `setup.py` is run.

**Comment by tonygrue** [comment]
Hitting this issue when doing 'pip install -r requirements.txt' with a requirements.txt that includes pyautogui (which is dependant on pyscreeze); even when pillow is first listed in the requirements.txt.   If I first 'pip install pillow' then install from my requirements.txt I can work around it.

**Comment by Wykleph** [comment]
No idea how to work around this.  Trying to install pyautogui, and it fails when trying to install pyscreeze due to the `from PIL import Image` that is ran.  Can't install pyautogui or pyscreeze due to this issue.

**Comment by divkis01** [comment]
@Wykleph : Installing pillow before installing pyautogui makes it work.

**Comment by Wykleph** [comment]
@divkis01, I did try this when I was troubleshooting, however it did not work. I ended up giving up on this particular library, so I don't have any more information to provide.
