### ISSUE TITLE
installation breaks with import error

### ISSUE THREAD

**Issue by benzolius** [asweigart/pyscreeze#20]
Installing by pip into a Python 3 virtualenv on Ubuntu 14.04 installation breaks with this traceback:

Collecting Pillow (from pyautogui)
  Using cached Pillow-3.2.0.zip
Collecting pyscreeze (from pyautogui)
  Using cached PyScreeze-0.1.8.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-iwkavk3q/pyscreeze/setup.py", line 6, in <module>
        version=**import**('pyscreeze').**version**,
      File "/tmp/pip-build-iwkavk3q/pyscreeze/pyscreeze/**init**.py", line 21, in <module>
        from PIL import Image
    ImportError: No module named 'PIL'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-iwkavk3q/pyscreeze/

However if I install Pillow first, the installation works

**Comment by benzolius** [comment]
I've don't tested on Pyscreeze, but I guess an easy fix would be (pyscreeze/init.py):

try:
    from PIL import Image
except ImportError:
    pass

**Comment by asweigart** [comment]
Fixed in https://github.com/asweigart/pyscreeze/pull/17
