### ISSUE TITLE
expose confidence parameter in _locateAll_opencv

### ISSUE THREAD

**Issue by jeremygray** [asweigart/pyscreeze#30]
per https://github.com/asweigart/pyautogui/issues/150

**Comment by jeremygray** [comment]
oops, its already exposed! that was easy

**Comment by umybuddy** [comment]
Just trying to write a script that uses pyautogui and the tolerance feature would be nice. Would you be able to provide more instructions of how to expose confidence parameter? I'm fairly new at scripting with python and I am unsure of how to do this. Any help would be greatly appreciated.

**Comment by jeremygray** [comment]
@umybuddy see the discussion here: https://github.com/asweigart/pyautogui/issues/150 you need to have opencv installed, and then call the pyautogui locate function with `confidence=x`, where 0 < x <= 1. 1 == pixel perfect match. This will not work without the opencv library

**Comment by umybuddy** [comment]
Got it to work thanks for the help!
