### ISSUE TITLE
hat if you want to find the coordinates of the specified picture from the specified picture?

### ISSUE THREAD

**Issue by XDSwang** [asweigart/pyscreeze#54]

**Comment by deepio** [comment]
Then use the locate function from the documentation:

```python
locate(needleImage, haystackImage, grayscale=False)
```

Returns (left, top, width, height) coordinate of first found instance of needleImage in haystackImage. Returns None if not found on the screen.

**Comment by XDSwang** [comment]
@deepio I used it and then 
![QQ图片20200510073905](https://user-images.githubusercontent.com/39626582/81487615-64f65580-9291-11ea-8fa7-f50dd3f91491.png)

**Comment by deepio** [comment]
Maybe this is lost in translation? That error says the small image you're looking for is in fact bigger than the large image that's supposed to contain it. Check your image dimensions again.

**Comment by XDSwang** [comment]
@deepio Sorry, it suddenly occurred to me that the first one in the front is the little picture, and the second one is the big picture.It was successful

**Comment by deepio** [comment]
@XDSwang problem solved, you can close the issue now. Or @asweigart you can probably close this issue too.
