### ISSUE TITLE
Support Python 3.9 - update Pillow dependency

### ISSUE THREAD

**Issue by oidualc** [asweigart/pyscreeze#64]
In my testing with [pyautogui](https://github.com/asweigart/pyautogui) in Python 3.9, currently this package crashes with a `NameError: name 'Image' is not defined` due to an old Pillow dependency, that is resolved just updating the Pillow package version.

**Comment by Avasam** [comment]
@oidualc @asweigart This should already be resolved by https://github.com/asweigart/pyscreeze/commit/7300a04568465342e16ba06274a4cb50667ff6e3 right ?
