### ISSUE TITLE
Pillow version check on Mac OS fails. Suggesting fix.

### ISSUE THREAD

**Issue by a-alak** [asweigart/pyscreeze#98]
Hi all,

_screenshot_osx function throws an error, because of the Pillow version check.
Basically a tuple with one string is compared to a tuple with ints.
I suggest adding these two lines to the top of the function:

`if isinstance(PIL__version__, str):`
`    PIL__version__ = (int(value) for value in PIL__version__.split('.'))`

This creates a generator so when tuple(PIL__version__) is called it will create (x, y, z) instead of ("x.y.z") and the comparison can work as expected.

**Comment by pokir** [comment]
I am having the same issue.

**Comment by Joymaker** [comment]
Perhaps this is more "correct" and forward-looking?

At the top:
`from packaging.version import Version`

In the function:
    `if Version(PIL__version__) < Version("6.2.1"):`

This is working smoothly for me.

**Comment by asweigart** [comment]
This fix is going into 1.0.0. Thanks!
